### ISSUE TITLE
Bad Spell Check

### ISSUE THREAD

**Issue by jakekinsella** [Math-ias/scdr#4]
Well supposedly test is not a word and must be changed to lest...
**EDIT**: Wasn't latest version _resolved_

**Comment by Math-ias** [comment]
Hello Jake, have you pulled the latest version? If this is so test is not in /usr/share/dict/words, something specific to Mac OSX.

**EDIT**: Tested on Ubuntu 14, could not reproduce it, maybe I'll make a patch for Mac OSX in the future. Can you perhaps give me a link to your /usr/share/dict/words file?
